name: Mosaic Republic
favicon: null
layout_spectrum: 0.27797
typography_spectrum: 0.24576
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Mosaic Republic    Qualified Mosaic Artisans '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fe0000'
    - '#000000'
    - '#4bd9ff'
    - '#127c09'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
