collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7311828
  lightness: 0.4928315
  brandStrength: 0.8136201
  brandColors:
    - '#FFFFFF'
    - '#F1221C'
    - '#000000'
    - '#FDCA8B'
    - '#01A5E1'
  rhythmicContrast: 0.4426523
typography_spectrum: 0.1344086
layout_spectrum: 1
name: Mosaic Republic
